feat(config): Aether Start
Gilded-Games/The-Aether pull request #1575
Opened 2023-07-09 08:11 UTC by bconlon1

closes #1557

2023-07-09 22:00 UTC, Jonathing requested changes
Unless the user has Configured installed (whose GUI configs allow for default server configs on world creation), it will be very hard for a client, who wants to create a single player world, to have this config boolean magically enabled. It might be prudent to create a built-in datapack that simply triggers spawning the player in the Aether as well.

2023-07-09 23:05 UTC, bconlon1 commented
@Jonathing 
This config isn't intended for datapack makers and not really average players creating a world, as is said in the config comment. Either way though, this is still able to be set with `defaultconfigs` by anyone.

2023-07-09 23:05 UTC, bconlon1 commented on src/main/java/com/aetherteam/aether/capability/player/AetherPlayerCapability.java
> +	private boolean canSpawnInAether = true;
This value needs to be set to NBT.

2023-07-09 23:06 UTC, Jonathing commented
Well, the modpack developers can figure it out. 😃👍

2023-07-09 23:08 UTC, bconlon1 commented
Meant to say *is intended for modpack players.

2023-07-10 21:14 UTC, raptor494 approved these changes

2023-07-10 21:46 UTC, merged