feat: dart shooter balance experiment
Gilded-Games/The-Aether pull request #1735
Opened 2023-09-19 15:57 UTC by OscarPayn

reduced firing speed
slightly reduced projectile speed
reduced damage
reduced power enchantment modifier

2023-09-19 18:13 UTC, Sto3IV commented on src/main/java/com/aetherteam/aether/entity/projectile/dart/EnchantedDart.java
from 6.0 to 4.0 will be more fine

2023-09-19 18:13 UTC, Sto3IV commented on src/main/java/com/aetherteam/aether/entity/projectile/dart/GoldenDart.java
no

2023-09-19 18:14 UTC, Sto3IV commented on src/main/java/com/aetherteam/aether/entity/projectile/dart/PoisonDart.java
no. current numbers if fine

2023-09-19 18:15 UTC, Sto3IV commented on src/main/java/com/aetherteam/aether/item/combat/DartShooterItem.java
depends on Minecraft difficulty will be better.

2023-09-19 18:15 UTC, Sto3IV requested changes
easy difficulty = ez mode
hard difficulty = please no. no darts.... i'm falling. ded

2023-09-19 21:00 UTC, OscarPayn commented
> easy difficulty = ez mode hard difficulty = please no. no darts.... i'm falling. ded

Difficulty settings don't generally affect player functionality in vanilla, I do not think that would be a good idea.

The damage numbers Ive chosen are based on the amount of hits required to kill some of our tankier mobs like Valkyries. If the value is too high the dart shooters very very quickly outcompete even the highest enchanted swords. The values I've proposed here put the dart shooters just below swords in terms of damage output, but they also still retain the very impactful strength of being zero-gravity projectiles. So I think there would be an argument for perhaps debuffing them further. But I'd like people to actually test these values first and see how they feel rather than just commenting on the numbers themselves.

2023-09-21 15:23 UTC, bconlon1 approved these changes
lgtm

2023-09-21 15:26 UTC, merged