feat: jar size reduction
Gilded-Games/The-Aether pull request #2014
Opened 2024-01-28 19:58 UTC by rhysdh540

changes
 - compressed all png images with etc and oxipng
 - compressed all sounds with optivorbis
 - added machete (a gradle plugin) to minify json files at build time
 - removed datagen `.cache/` folder from jar

should save at least 2-3 megabytes, probably more when combined with https://github.com/The-Aether-Team/Nitrogen/pull/21

I didn't realize that there was a commit naming policy, if necessary I can redo this, but squashing this pr should fix it anyways
---
I agree to the Contributor License Agreement (CLA).

2024-01-28 20:02 UTC, bconlon1 commented
I can't check this out at the moment, but do block textures like leaves still have their transparent cutout parts made black when opaque with fast graphics? That has been an issue in the past with texture optimization attempts.

2024-01-28 20:58 UTC, rhysdh540 commented
They do.
![leaves](https://github.com/The-Aether-Team/The-Aether/assets/98863820/c57982d6-ea53-462b-a070-ad230fd8444f)
(the berry bush not becoming opaque also happens with the non-pr branch)

2024-03-20 18:37 UTC, bconlon1 commented
Apologies for not having been able to get around to reviewing this yet. We've been in the middle of a porting period which has been taking longer than expected, so I plan to look more in-depth at this after we release the 1.20.4 port and focus on the 1.5.0 update milestone.

2024-04-03 01:48 UTC, mrjasonn commented
I suggest to please update the description to reflect that you are not using machete anymore, it will probably be easier for the Aether team. Thanks!

2024-04-03 11:36 UTC, rhysdh540 commented
sorry! it should be more accurate now.

2024-04-16 14:37 UTC, mrjasonn requested changes

2024-04-16 14:37 UTC, mrjasonn commented on build.gradle
> +import groovy.json.JsonOutput
Would recommend to use gson instead for both parsing the json and outputting the json because it can handle comments in json files. I have tested using gson instead in my own mod that is a fabric mod and still minifies the jsons properly.

2024-04-16 23:07 UTC, rhysdh540 commented on build.gradle
> +import groovy.json.JsonOutput
done!

2024-04-19 00:29 UTC, mrjasonn requested changes
I would also suggest you can switch the branch to 1.20.4 and account for the updated textures that need to be compressed such as the updated berry bush texture

2024-04-21 21:12 UTC, rhysdh540 commented
Should I do that by creating a new PR or by switching the branch on this one and merging everything?

2024-04-25 08:44 UTC, mrjasonn commented
> Should I do that by creating a new PR or by switching the branch on this one and merging everything?

Switching branch and merge everything then encompass new things and updated things etc (just would be my personal preference)

2024-06-19 00:53 UTC, bconlon1 commented
Ended up implementing a different implementation of the first iteration of this as #2196. Keeping the image optimizations to the script instead of manually updating them on the repository is better for future-proofing, and the sound designers are more in charge of the audio optimizations. Using the machete plugin will also likely be better for maintainability from its simplicity.

2024-06-19 00:53 UTC, closed without merging