improv: Mixin cleanup for compat and general improvements
Gilded-Games/The-Aether pull request #2152
Opened 2024-05-05 04:29 UTC by Alexandra-Myers

After perusing through the mixins to see what I could do (mixins tend to be a common source of issues, which I intended to solve), I noticed that none of them used MixinExtras features. 

While this isn't strictly required, and, indeed, should be used when it is proper practice to do so, there were several scenarios where it would be best practice, for mod compatibility and otherwise, to use it.

Hence, most of these changes are in regard to using MixinExtras in places where it should be.

However, there is another notable change. I added an interface for obtaining the identifier for a specific accessory's accessory slot in order to decrease uses of identical code repeated several times in different circumstances which could be unified to be the same.

---

I agree to the Contributor License Agreement (CLA).

2024-05-05 04:37 UTC, Alexandra-Myers commented on src/main/java/com/aetherteam/aether/mixin/mixins/common/AbstractArrowMixin.java
> -                            for (int i = 0; i < 1; i++) {
This for loop will only ever run once, and can thus be replaced with just a single method call.

2024-05-05 20:29 UTC, bconlon1 requested changes
Would you be able to split the accessory changes and the mixin changes into separate PRs?

2024-05-05 21:23 UTC, Alexandra-Myers commented
> Would you be able to split the accessory changes and the mixin changes into separate PRs?

Yes, admittedly I did it in one commit so it is rather difficult, but yes.

2024-05-05 22:34 UTC, Alexandra-Myers commented
Done.

2024-05-09 16:13 UTC, Alexandra-Myers commented
I realised that if this PR were to merge either before or after #2141, it would cause a merge conflict. I decided to revert FeatureMixin for this reason.

2024-05-14 00:41 UTC, Alexandra-Myers commented
?

2024-05-14 01:22 UTC, Alexandra-Myers commented
should be ready now

2024-05-14 01:26 UTC, bconlon1 approved these changes
lgtm

2024-05-14 01:32 UTC, merged