menu changes
Gilded-Games/The-Aether pull request #631
Opened 2022-05-22 16:40 UTC by Kelvin285

I think I've fixed my github fork!  Had to delete everything and fork it again.  Here's the menu changes with the custom title screen background.

2022-05-22 18:41 UTC, bconlon1 requested changes
In general you also have various NPE warnings for calling certain methods that should maybe have checks for safety; even if vanilla works fine with them there's no telling what other mods will do.

2022-05-22 18:41 UTC, bconlon1 commented on src/main/java/com/gildedgames/aether/client/event/listeners/OverlayListener.java
> +        var world = (ServerLevel)player.getCommandSenderWorld();
This variable seems to be unused, not sure if there's any reason in leaving it in.

2022-05-22 18:41 UTC, bconlon1 commented on src/main/java/com/gildedgames/aether/client/gui/screen/menu/AetherTitleScreen.java
> +			if (AetherWorldDisplayHelper.loadedLevel == null || !AetherConfig.CLIENT.enable_world_preview.get() || Minecraft.getInstance().level == null) this.panorama.render(partialTicks, Mth.clamp(f, 0.0F,
Might be better to just wrap the entire panorama render code in this check instead of the blits.

2022-05-22 18:41 UTC, bconlon1 commented on src/main/java/com/gildedgames/aether/client/gui/screen/menu/AetherWorldDisplayHelper.java
> +        Minecraft minecraft = Minecraft.getInstance();
Unused?

2022-05-22 18:41 UTC, bconlon1 commented on src/main/java/com/gildedgames/aether/client/gui/screen/menu/AetherWorldDisplayHelper.java
> +                //this.minecraft.forceSetScreen(new GenericDirtMessageScreen(new TranslatableComponent("selectWorld.data_read")));
If this is no longer needed it can probably be removed.

2022-05-22 18:41 UTC, bconlon1 commented on src/main/java/com/gildedgames/aether/core/mixin/mixins/client/MinecraftMixin.java
> +            AetherWorldDisplayHelper.loadingLevel = false;
This seems redundant if loadingLevel is already false, unless I'm misunderstanding something here.

2022-05-22 18:41 UTC, bconlon1 commented on src/main/java/com/gildedgames/aether/core/mixin/mixins/client/MinecraftMixin.java
> +                //minecraft.getSingleplayerServer().stopServer();
Is this code needed anymore?

2022-05-22 18:42 UTC, bconlon1 commented
There's some minor formatting critiques I have as well but I can clean those up myself later since they're nitpicky.

2022-05-22 19:13 UTC, bconlon1 commented on src/main/java/com/gildedgames/aether/client/gui/screen/menu/AetherTitleScreen.java
> +			if (AetherWorldDisplayHelper.loadedLevel == null || !AetherConfig.CLIENT.enable_world_preview.get() || Minecraft.getInstance().level == null) this.panorama.render(partialTicks, Mth.clamp(f, 0.0F,
Actually I'm wondering if this is even necessary if you have the mixin.

2022-05-22 20:02 UTC, Kelvin285 commented on src/main/java/com/gildedgames/aether/client/gui/screen/menu/AetherTitleScreen.java
> +			if (AetherWorldDisplayHelper.loadedLevel == null || !AetherConfig.CLIENT.enable_world_preview.get() || Minecraft.getInstance().level == null) this.panorama.render(partialTicks, Mth.clamp(f, 0.0F,
yeah I added the mixin later and forgot to remove that part of the code.  I'll remove it now.  It doesn't really need to stay there anymore.

2022-05-22 20:04 UTC, Kelvin285 commented on src/main/java/com/gildedgames/aether/client/gui/screen/menu/AetherWorldDisplayHelper.java
> +                //this.minecraft.forceSetScreen(new GenericDirtMessageScreen(new TranslatableComponent("selectWorld.data_read")));
didn't even notice that part of the code was there.  I copied those three lines over from another class and modified them.  I was wondering why that sound kept playing lol

2022-05-22 20:08 UTC, Kelvin285 commented on src/main/java/com/gildedgames/aether/core/mixin/mixins/client/MinecraftMixin.java
> +            AetherWorldDisplayHelper.loadingLevel = false;
The menu variables should only be set to null when leaving the menu screen, but clearLevel is called whenever a world is loaded so I have to put that there otherwise it will clear all the menu variables while it's loading a world file for the menu background and then you won't be able to see anything.

2022-05-22 20:09 UTC, Kelvin285 commented on src/main/java/com/gildedgames/aether/core/mixin/mixins/client/MinecraftMixin.java
> +                //minecraft.getSingleplayerServer().stopServer();
if I don't halt the integrated server when switching between levels the game crashes because the menu world has to be loaded without a session lock.  Halting the integrated server gives the game time to clear everything before switching to the next world and restarting the server.

2022-05-23 01:27 UTC, bconlon1 commented on src/main/java/com/gildedgames/aether/client/gui/screen/menu/AetherWorldDisplayHelper.java
> +                //this.minecraft.forceSetScreen(new GenericDirtMessageScreen(new TranslatableComponent("selectWorld.data_read")));
I meant to just point out the commented out code. Thank you GitHub.

2022-05-23 01:28 UTC, bconlon1 commented on src/main/java/com/gildedgames/aether/core/mixin/mixins/client/MinecraftMixin.java
> +            AetherWorldDisplayHelper.loadingLevel = false;
I was meaning to only point out the loadingLevel = false line.

2022-05-23 01:28 UTC, bconlon1 commented on src/main/java/com/gildedgames/aether/core/mixin/mixins/client/MinecraftMixin.java
> +                //minecraft.getSingleplayerServer().stopServer();
I was meaning to only point out the commented code.

2022-05-25 03:15 UTC, bconlon1 approved these changes
lgtm

2022-05-25 03:15 UTC, merged