refactor: NBT Fixes
Gilded-Games/The-Aether pull request #732
Opened 2022-07-21 23:17 UTC by bconlon1

- [ ] Closes #731.
- [ ] Parachute behavior more accurate to original mod (e.g. rotation and speed).

2022-07-25 21:55 UTC, Drullkus requested changes, later dismissed
I don't understand what `DungeonType`s are for. These are redundant since these can already be 1:1'd to the structure system

2022-07-25 22:06 UTC, Burning-Cactus requested changes

2022-07-25 22:06 UTC, Burning-Cactus commented on src/main/java/com/gildedgames/aether/entity/miscellaneous/Parachute.java
> +            AetherPacketHandler.sendToAll(new ExplosionParticlePacket(this.getId()));
This probably doesn't need to be sent to all clients.

2022-07-25 22:06 UTC, Burning-Cactus commented on src/main/java/com/gildedgames/aether/entity/miscellaneous/Parachute.java
> +        for (int i = 0; i < 10; i++) {
We should probably stop sending packets in loops, and instead include a number of iterations that the client should go through in a loop so we minimize the number of packets sent.

2022-07-26 03:56 UTC, Burning-Cactus approved these changes
Looks good to me!

2022-07-26 04:02 UTC, merged